apiVersion: v1
kind: Service
metadata:
  name: colorapi-canary-svc
spec:
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: colorapi  

---
apiVersion: v1
kind: Service
metadata:
  name: colorapi-stable-svc
spec:
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: colorapi  